// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: grpc/agent_service.proto

package agent_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobDescription  string                 `protobuf:"bytes,3,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	Skills          []string               `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	Location        string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	ExperienceLevel string                 `protobuf:"bytes,6,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_grpc_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_grpc_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *JobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JobRequest) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

func (x *JobRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *JobRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Matches       []*JobMatch            `protobuf:"bytes,4,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_grpc_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_grpc_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *JobResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobResponse) GetMatches() []*JobMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type JobMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	MatchScore    float64                `protobuf:"fixed64,5,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMatch) Reset() {
	*x = JobMatch{}
	mi := &file_grpc_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMatch) ProtoMessage() {}

func (x *JobMatch) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMatch.ProtoReflect.Descriptor instead.
func (*JobMatch) Descriptor() ([]byte, []int) {
	return file_grpc_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *JobMatch) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobMatch) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobMatch) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *JobMatch) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobMatch) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *JobMatch) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CandidateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobTitle        string                 `protobuf:"bytes,3,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Company         string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	RequiredSkills  []string               `protobuf:"bytes,5,rep,name=required_skills,json=requiredSkills,proto3" json:"required_skills,omitempty"`
	Location        string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	ExperienceLevel string                 `protobuf:"bytes,7,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CandidateRequest) Reset() {
	*x = CandidateRequest{}
	mi := &file_grpc_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateRequest) ProtoMessage() {}

func (x *CandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateRequest.ProtoReflect.Descriptor instead.
func (*CandidateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *CandidateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CandidateRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CandidateRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *CandidateRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CandidateRequest) GetRequiredSkills() []string {
	if x != nil {
		return x.RequiredSkills
	}
	return nil
}

func (x *CandidateRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CandidateRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

type CandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Matches       []*CandidateMatch      `protobuf:"bytes,4,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateResponse) Reset() {
	*x = CandidateResponse{}
	mi := &file_grpc_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse) ProtoMessage() {}

func (x *CandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse.ProtoReflect.Descriptor instead.
func (*CandidateResponse) Descriptor() ([]byte, []int) {
	return file_grpc_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *CandidateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CandidateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CandidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CandidateResponse) GetMatches() []*CandidateMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type CandidateMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	MatchScore    float64                `protobuf:"fixed64,4,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	Skills        []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Experience    string                 `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateMatch) Reset() {
	*x = CandidateMatch{}
	mi := &file_grpc_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateMatch) ProtoMessage() {}

func (x *CandidateMatch) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateMatch.ProtoReflect.Descriptor instead.
func (*CandidateMatch) Descriptor() ([]byte, []int) {
	return file_grpc_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *CandidateMatch) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *CandidateMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CandidateMatch) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CandidateMatch) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *CandidateMatch) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CandidateMatch) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *CandidateMatch) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_grpc_agent_service_proto protoreflect.FileDescriptor

const file_grpc_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x18grpc/agent_service.proto\x12\x14jobzee.agent_service\"\xcc\x01\n" +
	"\n" +
	"JobRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fjob_description\x18\x03 \x01(\tR\x0ejobDescription\x12\x16\n" +
	"\x06skills\x18\x04 \x03(\tR\x06skills\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12)\n" +
	"\x10experience_level\x18\x06 \x01(\tR\x0fexperienceLevel\"\x98\x01\n" +
	"\vJobResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\amatches\x18\x04 \x03(\v2\x1e.jobzee.agent_service.JobMatchR\amatches\"\xb0\x01\n" +
	"\bJobMatch\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1f\n" +
	"\vmatch_score\x18\x05 \x01(\x01R\n" +
	"matchScore\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xef\x01\n" +
	"\x10CandidateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tjob_title\x18\x03 \x01(\tR\bjobTitle\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12'\n" +
	"\x0frequired_skills\x18\x05 \x03(\tR\x0erequiredSkills\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12)\n" +
	"\x10experience_level\x18\a \x01(\tR\x0fexperienceLevel\"\xa4\x01\n" +
	"\x11CandidateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12>\n" +
	"\amatches\x18\x04 \x03(\v2$.jobzee.agent_service.CandidateMatchR\amatches\"\xd2\x01\n" +
	"\x0eCandidateMatch\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vmatch_score\x18\x04 \x01(\x01R\n" +
	"matchScore\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\tR\n" +
	"experience\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation2\xd4\x01\n" +
	"\fAgentService\x12X\n" +
	"\x11ProcessJobRequest\x12 .jobzee.agent_service.JobRequest\x1a!.jobzee.agent_service.JobResponse\x12j\n" +
	"\x17ProcessCandidateRequest\x12&.jobzee.agent_service.CandidateRequest\x1a'.jobzee.agent_service.CandidateResponseBQ\n" +
	"\x17com.jobzee.agentserviceP\x01Z4github.com/jobzee/jobzee-backend/proto/agent_serviceb\x06proto3"

var (
	file_grpc_agent_service_proto_rawDescOnce sync.Once
	file_grpc_agent_service_proto_rawDescData []byte
)

func file_grpc_agent_service_proto_rawDescGZIP() []byte {
	file_grpc_agent_service_proto_rawDescOnce.Do(func() {
		file_grpc_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_agent_service_proto_rawDesc), len(file_grpc_agent_service_proto_rawDesc)))
	})
	return file_grpc_agent_service_proto_rawDescData
}

var file_grpc_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_agent_service_proto_goTypes = []any{
	(*JobRequest)(nil),        // 0: jobzee.agent_service.JobRequest
	(*JobResponse)(nil),       // 1: jobzee.agent_service.JobResponse
	(*JobMatch)(nil),          // 2: jobzee.agent_service.JobMatch
	(*CandidateRequest)(nil),  // 3: jobzee.agent_service.CandidateRequest
	(*CandidateResponse)(nil), // 4: jobzee.agent_service.CandidateResponse
	(*CandidateMatch)(nil),    // 5: jobzee.agent_service.CandidateMatch
}
var file_grpc_agent_service_proto_depIdxs = []int32{
	2, // 0: jobzee.agent_service.JobResponse.matches:type_name -> jobzee.agent_service.JobMatch
	5, // 1: jobzee.agent_service.CandidateResponse.matches:type_name -> jobzee.agent_service.CandidateMatch
	0, // 2: jobzee.agent_service.AgentService.ProcessJobRequest:input_type -> jobzee.agent_service.JobRequest
	3, // 3: jobzee.agent_service.AgentService.ProcessCandidateRequest:input_type -> jobzee.agent_service.CandidateRequest
	1, // 4: jobzee.agent_service.AgentService.ProcessJobRequest:output_type -> jobzee.agent_service.JobResponse
	4, // 5: jobzee.agent_service.AgentService.ProcessCandidateRequest:output_type -> jobzee.agent_service.CandidateResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_agent_service_proto_init() }
func file_grpc_agent_service_proto_init() {
	if File_grpc_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_agent_service_proto_rawDesc), len(file_grpc_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_agent_service_proto_goTypes,
		DependencyIndexes: file_grpc_agent_service_proto_depIdxs,
		MessageInfos:      file_grpc_agent_service_proto_msgTypes,
	}.Build()
	File_grpc_agent_service_proto = out.File
	file_grpc_agent_service_proto_goTypes = nil
	file_grpc_agent_service_proto_depIdxs = nil
}
