// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: grpc/candidate_service.proto

package candidate_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Experience entity
type Experience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Current       bool                   `protobuf:"varint,6,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_grpc_candidate_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{0}
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Experience) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Experience) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Experience) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Experience) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

// Education entity
type Education struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Institution   string                 `protobuf:"bytes,1,opt,name=institution,proto3" json:"institution,omitempty"`
	Degree        string                 `protobuf:"bytes,2,opt,name=degree,proto3" json:"degree,omitempty"`
	FieldOfStudy  string                 `protobuf:"bytes,3,opt,name=field_of_study,json=fieldOfStudy,proto3" json:"field_of_study,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Grade         string                 `protobuf:"bytes,6,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_grpc_candidate_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{1}
}

func (x *Education) GetInstitution() string {
	if x != nil {
		return x.Institution
	}
	return ""
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetFieldOfStudy() string {
	if x != nil {
		return x.FieldOfStudy
	}
	return ""
}

func (x *Education) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Education) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Education) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

// Candidate entity
type Candidate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone             string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Location          string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Skills            []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	Experience        []*Experience          `protobuf:"bytes,7,rep,name=experience,proto3" json:"experience,omitempty"`
	Education         []*Education           `protobuf:"bytes,8,rep,name=education,proto3" json:"education,omitempty"`
	ExperienceYears   int32                  `protobuf:"varint,9,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	PreferredRoles    []string               `protobuf:"bytes,10,rep,name=preferred_roles,json=preferredRoles,proto3" json:"preferred_roles,omitempty"`
	SalaryExpectation string                 `protobuf:"bytes,11,opt,name=salary_expectation,json=salaryExpectation,proto3" json:"salary_expectation,omitempty"`
	Status            string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_grpc_candidate_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{2}
}

func (x *Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Candidate) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Candidate) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Candidate) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Candidate) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Candidate) GetExperience() []*Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *Candidate) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *Candidate) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *Candidate) GetPreferredRoles() []string {
	if x != nil {
		return x.PreferredRoles
	}
	return nil
}

func (x *Candidate) GetSalaryExpectation() string {
	if x != nil {
		return x.SalaryExpectation
	}
	return ""
}

func (x *Candidate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Candidate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Candidate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Create candidate request
type CreateCandidateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone             string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Location          string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Skills            []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Experience        []*Experience          `protobuf:"bytes,6,rep,name=experience,proto3" json:"experience,omitempty"`
	Education         []*Education           `protobuf:"bytes,7,rep,name=education,proto3" json:"education,omitempty"`
	ExperienceYears   int32                  `protobuf:"varint,8,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	PreferredRoles    []string               `protobuf:"bytes,9,rep,name=preferred_roles,json=preferredRoles,proto3" json:"preferred_roles,omitempty"`
	SalaryExpectation string                 `protobuf:"bytes,10,opt,name=salary_expectation,json=salaryExpectation,proto3" json:"salary_expectation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateCandidateRequest) Reset() {
	*x = CreateCandidateRequest{}
	mi := &file_grpc_candidate_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateRequest) ProtoMessage() {}

func (x *CreateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateRequest.ProtoReflect.Descriptor instead.
func (*CreateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCandidateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCandidateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCandidateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCandidateRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateCandidateRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateCandidateRequest) GetExperience() []*Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *CreateCandidateRequest) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *CreateCandidateRequest) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *CreateCandidateRequest) GetPreferredRoles() []string {
	if x != nil {
		return x.PreferredRoles
	}
	return nil
}

func (x *CreateCandidateRequest) GetSalaryExpectation() string {
	if x != nil {
		return x.SalaryExpectation
	}
	return ""
}

// Get candidate request
type GetCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateRequest) Reset() {
	*x = GetCandidateRequest{}
	mi := &file_grpc_candidate_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateRequest) ProtoMessage() {}

func (x *GetCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCandidateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// List candidates request
type ListCandidatesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PageSize           int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken          string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Location           string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Skills             []string               `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	MinExperienceYears int32                  `protobuf:"varint,5,opt,name=min_experience_years,json=minExperienceYears,proto3" json:"min_experience_years,omitempty"`
	MaxExperienceYears int32                  `protobuf:"varint,6,opt,name=max_experience_years,json=maxExperienceYears,proto3" json:"max_experience_years,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListCandidatesRequest) Reset() {
	*x = ListCandidatesRequest{}
	mi := &file_grpc_candidate_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatesRequest) ProtoMessage() {}

func (x *ListCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatesRequest.ProtoReflect.Descriptor instead.
func (*ListCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListCandidatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCandidatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCandidatesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListCandidatesRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListCandidatesRequest) GetMinExperienceYears() int32 {
	if x != nil {
		return x.MinExperienceYears
	}
	return 0
}

func (x *ListCandidatesRequest) GetMaxExperienceYears() int32 {
	if x != nil {
		return x.MaxExperienceYears
	}
	return 0
}

// List candidates response
type ListCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCandidatesResponse) Reset() {
	*x = ListCandidatesResponse{}
	mi := &file_grpc_candidate_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatesResponse) ProtoMessage() {}

func (x *ListCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatesResponse.ProtoReflect.Descriptor instead.
func (*ListCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListCandidatesResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ListCandidatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCandidatesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Update candidate request
type UpdateCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Candidate     *Candidate             `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateRequest) Reset() {
	*x = UpdateCandidateRequest{}
	mi := &file_grpc_candidate_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateRequest) ProtoMessage() {}

func (x *UpdateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateRequest.ProtoReflect.Descriptor instead.
func (*UpdateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCandidateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCandidateRequest) GetCandidate() *Candidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

// Delete candidate request
type DeleteCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCandidateRequest) Reset() {
	*x = DeleteCandidateRequest{}
	mi := &file_grpc_candidate_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateRequest) ProtoMessage() {}

func (x *DeleteCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateRequest.ProtoReflect.Descriptor instead.
func (*DeleteCandidateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCandidateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Search candidates request
type SearchCandidatesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Query              string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Skills             []string               `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	Location           string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	MinExperienceYears int32                  `protobuf:"varint,4,opt,name=min_experience_years,json=minExperienceYears,proto3" json:"min_experience_years,omitempty"`
	MaxExperienceYears int32                  `protobuf:"varint,5,opt,name=max_experience_years,json=maxExperienceYears,proto3" json:"max_experience_years,omitempty"`
	PreferredRoles     []string               `protobuf:"bytes,6,rep,name=preferred_roles,json=preferredRoles,proto3" json:"preferred_roles,omitempty"`
	SalaryRange        string                 `protobuf:"bytes,7,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	PageSize           int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken          string                 `protobuf:"bytes,9,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchCandidatesRequest) Reset() {
	*x = SearchCandidatesRequest{}
	mi := &file_grpc_candidate_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCandidatesRequest) ProtoMessage() {}

func (x *SearchCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCandidatesRequest.ProtoReflect.Descriptor instead.
func (*SearchCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCandidatesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCandidatesRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *SearchCandidatesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SearchCandidatesRequest) GetMinExperienceYears() int32 {
	if x != nil {
		return x.MinExperienceYears
	}
	return 0
}

func (x *SearchCandidatesRequest) GetMaxExperienceYears() int32 {
	if x != nil {
		return x.MaxExperienceYears
	}
	return 0
}

func (x *SearchCandidatesRequest) GetPreferredRoles() []string {
	if x != nil {
		return x.PreferredRoles
	}
	return nil
}

func (x *SearchCandidatesRequest) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *SearchCandidatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchCandidatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Search candidates response
type SearchCandidatesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Candidates      []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	NextPageToken   string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount      int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	RelevanceScores []float32              `protobuf:"fixed32,4,rep,packed,name=relevance_scores,json=relevanceScores,proto3" json:"relevance_scores,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchCandidatesResponse) Reset() {
	*x = SearchCandidatesResponse{}
	mi := &file_grpc_candidate_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCandidatesResponse) ProtoMessage() {}

func (x *SearchCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCandidatesResponse.ProtoReflect.Descriptor instead.
func (*SearchCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCandidatesResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *SearchCandidatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *SearchCandidatesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchCandidatesResponse) GetRelevanceScores() []float32 {
	if x != nil {
		return x.RelevanceScores
	}
	return nil
}

// Get candidate stats request
type GetCandidateStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Skills        []string               `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	TimePeriod    string                 `protobuf:"bytes,3,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"` // daily, weekly, monthly, yearly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateStatsRequest) Reset() {
	*x = GetCandidateStatsRequest{}
	mi := &file_grpc_candidate_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateStatsRequest) ProtoMessage() {}

func (x *GetCandidateStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateStatsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCandidateStatsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetCandidateStatsRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetCandidateStatsRequest) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

// Candidate statistics
type CandidateStats struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	TotalCandidates             int32                  `protobuf:"varint,1,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"`
	ActiveCandidates            int32                  `protobuf:"varint,2,opt,name=active_candidates,json=activeCandidates,proto3" json:"active_candidates,omitempty"`
	CandidatesByLocation        map[string]int32       `protobuf:"bytes,3,rep,name=candidates_by_location,json=candidatesByLocation,proto3" json:"candidates_by_location,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CandidatesByExperienceLevel map[string]int32       `protobuf:"bytes,4,rep,name=candidates_by_experience_level,json=candidatesByExperienceLevel,proto3" json:"candidates_by_experience_level,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopSkills                   []string               `protobuf:"bytes,5,rep,name=top_skills,json=topSkills,proto3" json:"top_skills,omitempty"`
	TopPreferredRoles           []string               `protobuf:"bytes,6,rep,name=top_preferred_roles,json=topPreferredRoles,proto3" json:"top_preferred_roles,omitempty"`
	AverageExperienceYears      float32                `protobuf:"fixed32,7,opt,name=average_experience_years,json=averageExperienceYears,proto3" json:"average_experience_years,omitempty"`
	LastUpdated                 *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CandidateStats) Reset() {
	*x = CandidateStats{}
	mi := &file_grpc_candidate_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateStats) ProtoMessage() {}

func (x *CandidateStats) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_candidate_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateStats.ProtoReflect.Descriptor instead.
func (*CandidateStats) Descriptor() ([]byte, []int) {
	return file_grpc_candidate_service_proto_rawDescGZIP(), []int{12}
}

func (x *CandidateStats) GetTotalCandidates() int32 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

func (x *CandidateStats) GetActiveCandidates() int32 {
	if x != nil {
		return x.ActiveCandidates
	}
	return 0
}

func (x *CandidateStats) GetCandidatesByLocation() map[string]int32 {
	if x != nil {
		return x.CandidatesByLocation
	}
	return nil
}

func (x *CandidateStats) GetCandidatesByExperienceLevel() map[string]int32 {
	if x != nil {
		return x.CandidatesByExperienceLevel
	}
	return nil
}

func (x *CandidateStats) GetTopSkills() []string {
	if x != nil {
		return x.TopSkills
	}
	return nil
}

func (x *CandidateStats) GetTopPreferredRoles() []string {
	if x != nil {
		return x.TopPreferredRoles
	}
	return nil
}

func (x *CandidateStats) GetAverageExperienceYears() float32 {
	if x != nil {
		return x.AverageExperienceYears
	}
	return 0
}

func (x *CandidateStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_grpc_candidate_service_proto protoreflect.FileDescriptor

const file_grpc_candidate_service_proto_rawDesc = "" +
	"\n" +
	"\x1cgrpc/candidate_service.proto\x12\x18jobzee.candidate_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf0\x01\n" +
	"\n" +
	"Experience\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\bR\acurrent\"\xf3\x01\n" +
	"\tEducation\x12 \n" +
	"\vinstitution\x18\x01 \x01(\tR\vinstitution\x12\x16\n" +
	"\x06degree\x18\x02 \x01(\tR\x06degree\x12$\n" +
	"\x0efield_of_study\x18\x03 \x01(\tR\ffieldOfStudy\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x14\n" +
	"\x05grade\x18\x06 \x01(\tR\x05grade\"\xa9\x04\n" +
	"\tCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x12D\n" +
	"\n" +
	"experience\x18\a \x03(\v2$.jobzee.candidate_service.ExperienceR\n" +
	"experience\x12A\n" +
	"\teducation\x18\b \x03(\v2#.jobzee.candidate_service.EducationR\teducation\x12)\n" +
	"\x10experience_years\x18\t \x01(\x05R\x0fexperienceYears\x12'\n" +
	"\x0fpreferred_roles\x18\n" +
	" \x03(\tR\x0epreferredRoles\x12-\n" +
	"\x12salary_expectation\x18\v \x01(\tR\x11salaryExpectation\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x98\x03\n" +
	"\x16CreateCandidateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x12D\n" +
	"\n" +
	"experience\x18\x06 \x03(\v2$.jobzee.candidate_service.ExperienceR\n" +
	"experience\x12A\n" +
	"\teducation\x18\a \x03(\v2#.jobzee.candidate_service.EducationR\teducation\x12)\n" +
	"\x10experience_years\x18\b \x01(\x05R\x0fexperienceYears\x12'\n" +
	"\x0fpreferred_roles\x18\t \x03(\tR\x0epreferredRoles\x12-\n" +
	"\x12salary_expectation\x18\n" +
	" \x01(\tR\x11salaryExpectation\"%\n" +
	"\x13GetCandidateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xeb\x01\n" +
	"\x15ListCandidatesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x16\n" +
	"\x06skills\x18\x04 \x03(\tR\x06skills\x120\n" +
	"\x14min_experience_years\x18\x05 \x01(\x05R\x12minExperienceYears\x120\n" +
	"\x14max_experience_years\x18\x06 \x01(\x05R\x12maxExperienceYears\"\xa6\x01\n" +
	"\x16ListCandidatesResponse\x12C\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2#.jobzee.candidate_service.CandidateR\n" +
	"candidates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"k\n" +
	"\x16UpdateCandidateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\tcandidate\x18\x02 \x01(\v2#.jobzee.candidate_service.CandidateR\tcandidate\"(\n" +
	"\x16DeleteCandidateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcf\x02\n" +
	"\x17SearchCandidatesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06skills\x18\x02 \x03(\tR\x06skills\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x120\n" +
	"\x14min_experience_years\x18\x04 \x01(\x05R\x12minExperienceYears\x120\n" +
	"\x14max_experience_years\x18\x05 \x01(\x05R\x12maxExperienceYears\x12'\n" +
	"\x0fpreferred_roles\x18\x06 \x03(\tR\x0epreferredRoles\x12!\n" +
	"\fsalary_range\x18\a \x01(\tR\vsalaryRange\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\t \x01(\tR\tpageToken\"\xd3\x01\n" +
	"\x18SearchCandidatesResponse\x12C\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2#.jobzee.candidate_service.CandidateR\n" +
	"candidates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12)\n" +
	"\x10relevance_scores\x18\x04 \x03(\x02R\x0frelevanceScores\"o\n" +
	"\x18GetCandidateStatsRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x16\n" +
	"\x06skills\x18\x02 \x03(\tR\x06skills\x12\x1f\n" +
	"\vtime_period\x18\x03 \x01(\tR\n" +
	"timePeriod\"\xd4\x05\n" +
	"\x0eCandidateStats\x12)\n" +
	"\x10total_candidates\x18\x01 \x01(\x05R\x0ftotalCandidates\x12+\n" +
	"\x11active_candidates\x18\x02 \x01(\x05R\x10activeCandidates\x12x\n" +
	"\x16candidates_by_location\x18\x03 \x03(\v2B.jobzee.candidate_service.CandidateStats.CandidatesByLocationEntryR\x14candidatesByLocation\x12\x8e\x01\n" +
	"\x1ecandidates_by_experience_level\x18\x04 \x03(\v2I.jobzee.candidate_service.CandidateStats.CandidatesByExperienceLevelEntryR\x1bcandidatesByExperienceLevel\x12\x1d\n" +
	"\n" +
	"top_skills\x18\x05 \x03(\tR\ttopSkills\x12.\n" +
	"\x13top_preferred_roles\x18\x06 \x03(\tR\x11topPreferredRoles\x128\n" +
	"\x18average_experience_years\x18\a \x01(\x02R\x16averageExperienceYears\x12=\n" +
	"\flast_updated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1aG\n" +
	"\x19CandidatesByLocationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aN\n" +
	" CandidatesByExperienceLevelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\x8a\x06\n" +
	"\x10CandidateService\x12h\n" +
	"\x0fCreateCandidate\x120.jobzee.candidate_service.CreateCandidateRequest\x1a#.jobzee.candidate_service.Candidate\x12b\n" +
	"\fGetCandidate\x12-.jobzee.candidate_service.GetCandidateRequest\x1a#.jobzee.candidate_service.Candidate\x12s\n" +
	"\x0eListCandidates\x12/.jobzee.candidate_service.ListCandidatesRequest\x1a0.jobzee.candidate_service.ListCandidatesResponse\x12h\n" +
	"\x0fUpdateCandidate\x120.jobzee.candidate_service.UpdateCandidateRequest\x1a#.jobzee.candidate_service.Candidate\x12[\n" +
	"\x0fDeleteCandidate\x120.jobzee.candidate_service.DeleteCandidateRequest\x1a\x16.google.protobuf.Empty\x12y\n" +
	"\x10SearchCandidates\x121.jobzee.candidate_service.SearchCandidatesRequest\x1a2.jobzee.candidate_service.SearchCandidatesResponse\x12q\n" +
	"\x11GetCandidateStats\x122.jobzee.candidate_service.GetCandidateStatsRequest\x1a(.jobzee.candidate_service.CandidateStatsBY\n" +
	"\x1bcom.jobzee.candidateserviceP\x01Z8github.com/jobzee/jobzee-backend/proto/candidate_serviceb\x06proto3"

var (
	file_grpc_candidate_service_proto_rawDescOnce sync.Once
	file_grpc_candidate_service_proto_rawDescData []byte
)

func file_grpc_candidate_service_proto_rawDescGZIP() []byte {
	file_grpc_candidate_service_proto_rawDescOnce.Do(func() {
		file_grpc_candidate_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_candidate_service_proto_rawDesc), len(file_grpc_candidate_service_proto_rawDesc)))
	})
	return file_grpc_candidate_service_proto_rawDescData
}

var file_grpc_candidate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_grpc_candidate_service_proto_goTypes = []any{
	(*Experience)(nil),               // 0: jobzee.candidate_service.Experience
	(*Education)(nil),                // 1: jobzee.candidate_service.Education
	(*Candidate)(nil),                // 2: jobzee.candidate_service.Candidate
	(*CreateCandidateRequest)(nil),   // 3: jobzee.candidate_service.CreateCandidateRequest
	(*GetCandidateRequest)(nil),      // 4: jobzee.candidate_service.GetCandidateRequest
	(*ListCandidatesRequest)(nil),    // 5: jobzee.candidate_service.ListCandidatesRequest
	(*ListCandidatesResponse)(nil),   // 6: jobzee.candidate_service.ListCandidatesResponse
	(*UpdateCandidateRequest)(nil),   // 7: jobzee.candidate_service.UpdateCandidateRequest
	(*DeleteCandidateRequest)(nil),   // 8: jobzee.candidate_service.DeleteCandidateRequest
	(*SearchCandidatesRequest)(nil),  // 9: jobzee.candidate_service.SearchCandidatesRequest
	(*SearchCandidatesResponse)(nil), // 10: jobzee.candidate_service.SearchCandidatesResponse
	(*GetCandidateStatsRequest)(nil), // 11: jobzee.candidate_service.GetCandidateStatsRequest
	(*CandidateStats)(nil),           // 12: jobzee.candidate_service.CandidateStats
	nil,                              // 13: jobzee.candidate_service.CandidateStats.CandidatesByLocationEntry
	nil,                              // 14: jobzee.candidate_service.CandidateStats.CandidatesByExperienceLevelEntry
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 16: google.protobuf.Empty
}
var file_grpc_candidate_service_proto_depIdxs = []int32{
	15, // 0: jobzee.candidate_service.Experience.start_date:type_name -> google.protobuf.Timestamp
	15, // 1: jobzee.candidate_service.Experience.end_date:type_name -> google.protobuf.Timestamp
	15, // 2: jobzee.candidate_service.Education.start_date:type_name -> google.protobuf.Timestamp
	15, // 3: jobzee.candidate_service.Education.end_date:type_name -> google.protobuf.Timestamp
	0,  // 4: jobzee.candidate_service.Candidate.experience:type_name -> jobzee.candidate_service.Experience
	1,  // 5: jobzee.candidate_service.Candidate.education:type_name -> jobzee.candidate_service.Education
	15, // 6: jobzee.candidate_service.Candidate.created_at:type_name -> google.protobuf.Timestamp
	15, // 7: jobzee.candidate_service.Candidate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: jobzee.candidate_service.CreateCandidateRequest.experience:type_name -> jobzee.candidate_service.Experience
	1,  // 9: jobzee.candidate_service.CreateCandidateRequest.education:type_name -> jobzee.candidate_service.Education
	2,  // 10: jobzee.candidate_service.ListCandidatesResponse.candidates:type_name -> jobzee.candidate_service.Candidate
	2,  // 11: jobzee.candidate_service.UpdateCandidateRequest.candidate:type_name -> jobzee.candidate_service.Candidate
	2,  // 12: jobzee.candidate_service.SearchCandidatesResponse.candidates:type_name -> jobzee.candidate_service.Candidate
	13, // 13: jobzee.candidate_service.CandidateStats.candidates_by_location:type_name -> jobzee.candidate_service.CandidateStats.CandidatesByLocationEntry
	14, // 14: jobzee.candidate_service.CandidateStats.candidates_by_experience_level:type_name -> jobzee.candidate_service.CandidateStats.CandidatesByExperienceLevelEntry
	15, // 15: jobzee.candidate_service.CandidateStats.last_updated:type_name -> google.protobuf.Timestamp
	3,  // 16: jobzee.candidate_service.CandidateService.CreateCandidate:input_type -> jobzee.candidate_service.CreateCandidateRequest
	4,  // 17: jobzee.candidate_service.CandidateService.GetCandidate:input_type -> jobzee.candidate_service.GetCandidateRequest
	5,  // 18: jobzee.candidate_service.CandidateService.ListCandidates:input_type -> jobzee.candidate_service.ListCandidatesRequest
	7,  // 19: jobzee.candidate_service.CandidateService.UpdateCandidate:input_type -> jobzee.candidate_service.UpdateCandidateRequest
	8,  // 20: jobzee.candidate_service.CandidateService.DeleteCandidate:input_type -> jobzee.candidate_service.DeleteCandidateRequest
	9,  // 21: jobzee.candidate_service.CandidateService.SearchCandidates:input_type -> jobzee.candidate_service.SearchCandidatesRequest
	11, // 22: jobzee.candidate_service.CandidateService.GetCandidateStats:input_type -> jobzee.candidate_service.GetCandidateStatsRequest
	2,  // 23: jobzee.candidate_service.CandidateService.CreateCandidate:output_type -> jobzee.candidate_service.Candidate
	2,  // 24: jobzee.candidate_service.CandidateService.GetCandidate:output_type -> jobzee.candidate_service.Candidate
	6,  // 25: jobzee.candidate_service.CandidateService.ListCandidates:output_type -> jobzee.candidate_service.ListCandidatesResponse
	2,  // 26: jobzee.candidate_service.CandidateService.UpdateCandidate:output_type -> jobzee.candidate_service.Candidate
	16, // 27: jobzee.candidate_service.CandidateService.DeleteCandidate:output_type -> google.protobuf.Empty
	10, // 28: jobzee.candidate_service.CandidateService.SearchCandidates:output_type -> jobzee.candidate_service.SearchCandidatesResponse
	12, // 29: jobzee.candidate_service.CandidateService.GetCandidateStats:output_type -> jobzee.candidate_service.CandidateStats
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_grpc_candidate_service_proto_init() }
func file_grpc_candidate_service_proto_init() {
	if File_grpc_candidate_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_candidate_service_proto_rawDesc), len(file_grpc_candidate_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_candidate_service_proto_goTypes,
		DependencyIndexes: file_grpc_candidate_service_proto_depIdxs,
		MessageInfos:      file_grpc_candidate_service_proto_msgTypes,
	}.Build()
	File_grpc_candidate_service_proto = out.File
	file_grpc_candidate_service_proto_goTypes = nil
	file_grpc_candidate_service_proto_depIdxs = nil
}
