apiVersion: v1
kind: ConfigMap
metadata:
  name: jobzee-config
  namespace: jobzee
data:
  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "jobzee"
  DB_SSLMODE: "disable"

  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # Kafka configuration
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_TOPIC: "jobzee-events"

  # MinIO configuration
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_BUCKET: "jobzee"

  # Service ports
  API_PORT: "8080"
  JOB_SERVICE_PORT: "8081"
  CANDIDATE_SERVICE_PORT: "8082"
  AGENT_SERVICE_PORT: "8083"

  # Environment
  ENVIRONMENT: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jobzee-agents-config
  namespace: jobzee
data:
  # Agent configuration
  AGENT_ID: "job-finder-agent"
  AGENT_NAME: "Job Finder Agent"
  AGENT_VERSION: "1.0.0"

  # Kafka topics
  JOB_REQUESTS_TOPIC: "job-requests"
  JOB_MATCHES_TOPIC: "job-matches"
  CANDIDATE_REQUESTS_TOPIC: "candidate-requests"
  CANDIDATE_MATCHES_TOPIC: "candidate-matches"

  # Vector database
  VECTOR_DB_URL: "http://qdrant-service:6333"
  VECTOR_DB_COLLECTION: "jobs"

  # AI model
  MODEL_NAME: "gpt-4"
  MAX_TOKENS: "1000"
  TEMPERATURE: "0.1"

  # Matching configuration
  MIN_MATCH_SCORE: "0.7"
  MAX_RESULTS: "10"
  MIN_CANDIDATE_SCORE: "0.7"
  MAX_CANDIDATES: "10"

  # Logging
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # Health checks
  HEALTH_CHECK_INTERVAL: "30"
  MAX_PROCESSING_TIME: "300"
