// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: grpc/job_service.proto

package job_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job entity
type Job struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Company         string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Location        string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Requirements    []string               `protobuf:"bytes,6,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Skills          []string               `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
	ExperienceLevel string                 `protobuf:"bytes,8,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	SalaryRange     string                 `protobuf:"bytes,9,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	JobType         string                 `protobuf:"bytes,10,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	RemoteFriendly  bool                   `protobuf:"varint,11,opt,name=remote_friendly,json=remoteFriendly,proto3" json:"remote_friendly,omitempty"`
	Status          string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_grpc_job_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Job) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Job) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Job) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *Job) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *Job) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *Job) GetRemoteFriendly() bool {
	if x != nil {
		return x.RemoteFriendly
	}
	return false
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Create job request
type CreateJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company         string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Location        string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Requirements    []string               `protobuf:"bytes,5,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Skills          []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	ExperienceLevel string                 `protobuf:"bytes,7,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	SalaryRange     string                 `protobuf:"bytes,8,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	JobType         string                 `protobuf:"bytes,9,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	RemoteFriendly  bool                   `protobuf:"varint,10,opt,name=remote_friendly,json=remoteFriendly,proto3" json:"remote_friendly,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_grpc_job_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateJobRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateJobRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateJobRequest) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *CreateJobRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateJobRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *CreateJobRequest) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *CreateJobRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *CreateJobRequest) GetRemoteFriendly() bool {
	if x != nil {
		return x.RemoteFriendly
	}
	return false
}

// Get job request
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_grpc_job_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// List jobs request
type ListJobsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PageSize        int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken       string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Company         string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Location        string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	ExperienceLevel string                 `protobuf:"bytes,5,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	JobType         string                 `protobuf:"bytes,6,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	RemoteFriendly  bool                   `protobuf:"varint,7,opt,name=remote_friendly,json=remoteFriendly,proto3" json:"remote_friendly,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_grpc_job_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListJobsRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *ListJobsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListJobsRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *ListJobsRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ListJobsRequest) GetRemoteFriendly() bool {
	if x != nil {
		return x.RemoteFriendly
	}
	return false
}

// List jobs response
type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_grpc_job_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListJobsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Update job request
type UpdateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_grpc_job_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// Delete job request
type DeleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobRequest) Reset() {
	*x = DeleteJobRequest{}
	mi := &file_grpc_job_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRequest) ProtoMessage() {}

func (x *DeleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Search jobs request
type SearchJobsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Skills          []string               `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	Location        string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ExperienceLevel string                 `protobuf:"bytes,4,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	SalaryRange     string                 `protobuf:"bytes,5,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	RemoteFriendly  bool                   `protobuf:"varint,6,opt,name=remote_friendly,json=remoteFriendly,proto3" json:"remote_friendly,omitempty"`
	PageSize        int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken       string                 `protobuf:"bytes,8,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchJobsRequest) Reset() {
	*x = SearchJobsRequest{}
	mi := &file_grpc_job_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobsRequest) ProtoMessage() {}

func (x *SearchJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobsRequest.ProtoReflect.Descriptor instead.
func (*SearchJobsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchJobsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchJobsRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *SearchJobsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SearchJobsRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *SearchJobsRequest) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *SearchJobsRequest) GetRemoteFriendly() bool {
	if x != nil {
		return x.RemoteFriendly
	}
	return false
}

func (x *SearchJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Search jobs response
type SearchJobsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Jobs            []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageToken   string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount      int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	RelevanceScores []float32              `protobuf:"fixed32,4,rep,packed,name=relevance_scores,json=relevanceScores,proto3" json:"relevance_scores,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchJobsResponse) Reset() {
	*x = SearchJobsResponse{}
	mi := &file_grpc_job_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobsResponse) ProtoMessage() {}

func (x *SearchJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobsResponse.ProtoReflect.Descriptor instead.
func (*SearchJobsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{8}
}

func (x *SearchJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *SearchJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *SearchJobsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchJobsResponse) GetRelevanceScores() []float32 {
	if x != nil {
		return x.RelevanceScores
	}
	return nil
}

// Get job stats request
type GetJobStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	TimePeriod    string                 `protobuf:"bytes,3,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"` // daily, weekly, monthly, yearly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatsRequest) Reset() {
	*x = GetJobStatsRequest{}
	mi := &file_grpc_job_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatsRequest) ProtoMessage() {}

func (x *GetJobStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatsRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetJobStatsRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *GetJobStatsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetJobStatsRequest) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

// Job statistics
type JobStats struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalJobs             int32                  `protobuf:"varint,1,opt,name=total_jobs,json=totalJobs,proto3" json:"total_jobs,omitempty"`
	ActiveJobs            int32                  `protobuf:"varint,2,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	RemoteJobs            int32                  `protobuf:"varint,3,opt,name=remote_jobs,json=remoteJobs,proto3" json:"remote_jobs,omitempty"`
	JobsByExperienceLevel map[string]int32       `protobuf:"bytes,4,rep,name=jobs_by_experience_level,json=jobsByExperienceLevel,proto3" json:"jobs_by_experience_level,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	JobsByLocation        map[string]int32       `protobuf:"bytes,5,rep,name=jobs_by_location,json=jobsByLocation,proto3" json:"jobs_by_location,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	JobsByCompany         map[string]int32       `protobuf:"bytes,6,rep,name=jobs_by_company,json=jobsByCompany,proto3" json:"jobs_by_company,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopSkills             []string               `protobuf:"bytes,7,rep,name=top_skills,json=topSkills,proto3" json:"top_skills,omitempty"`
	LastUpdated           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JobStats) Reset() {
	*x = JobStats{}
	mi := &file_grpc_job_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStats) ProtoMessage() {}

func (x *JobStats) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_job_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStats.ProtoReflect.Descriptor instead.
func (*JobStats) Descriptor() ([]byte, []int) {
	return file_grpc_job_service_proto_rawDescGZIP(), []int{10}
}

func (x *JobStats) GetTotalJobs() int32 {
	if x != nil {
		return x.TotalJobs
	}
	return 0
}

func (x *JobStats) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *JobStats) GetRemoteJobs() int32 {
	if x != nil {
		return x.RemoteJobs
	}
	return 0
}

func (x *JobStats) GetJobsByExperienceLevel() map[string]int32 {
	if x != nil {
		return x.JobsByExperienceLevel
	}
	return nil
}

func (x *JobStats) GetJobsByLocation() map[string]int32 {
	if x != nil {
		return x.JobsByLocation
	}
	return nil
}

func (x *JobStats) GetJobsByCompany() map[string]int32 {
	if x != nil {
		return x.JobsByCompany
	}
	return nil
}

func (x *JobStats) GetTopSkills() []string {
	if x != nil {
		return x.TopSkills
	}
	return nil
}

func (x *JobStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_grpc_job_service_proto protoreflect.FileDescriptor

const file_grpc_job_service_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/job_service.proto\x12\x12jobzee.job_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xdf\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x06 \x03(\tR\frequirements\x12\x16\n" +
	"\x06skills\x18\a \x03(\tR\x06skills\x12)\n" +
	"\x10experience_level\x18\b \x01(\tR\x0fexperienceLevel\x12!\n" +
	"\fsalary_range\x18\t \x01(\tR\vsalaryRange\x12\x19\n" +
	"\bjob_type\x18\n" +
	" \x01(\tR\ajobType\x12'\n" +
	"\x0fremote_friendly\x18\v \x01(\bR\x0eremoteFriendly\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xce\x02\n" +
	"\x10CreateJobRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x05 \x03(\tR\frequirements\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x12)\n" +
	"\x10experience_level\x18\a \x01(\tR\x0fexperienceLevel\x12!\n" +
	"\fsalary_range\x18\b \x01(\tR\vsalaryRange\x12\x19\n" +
	"\bjob_type\x18\t \x01(\tR\ajobType\x12'\n" +
	"\x0fremote_friendly\x18\n" +
	" \x01(\bR\x0eremoteFriendly\"\x1f\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf2\x01\n" +
	"\x0fListJobsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12)\n" +
	"\x10experience_level\x18\x05 \x01(\tR\x0fexperienceLevel\x12\x19\n" +
	"\bjob_type\x18\x06 \x01(\tR\ajobType\x12'\n" +
	"\x0fremote_friendly\x18\a \x01(\bR\x0eremoteFriendly\"\x88\x01\n" +
	"\x10ListJobsResponse\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.jobzee.job_service.JobR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"M\n" +
	"\x10UpdateJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x03job\x18\x02 \x01(\v2\x17.jobzee.job_service.JobR\x03job\"\"\n" +
	"\x10DeleteJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x90\x02\n" +
	"\x11SearchJobsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06skills\x18\x02 \x03(\tR\x06skills\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12)\n" +
	"\x10experience_level\x18\x04 \x01(\tR\x0fexperienceLevel\x12!\n" +
	"\fsalary_range\x18\x05 \x01(\tR\vsalaryRange\x12'\n" +
	"\x0fremote_friendly\x18\x06 \x01(\bR\x0eremoteFriendly\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\b \x01(\tR\tpageToken\"\xb5\x01\n" +
	"\x12SearchJobsResponse\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.jobzee.job_service.JobR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12)\n" +
	"\x10relevance_scores\x18\x04 \x03(\x02R\x0frelevanceScores\"k\n" +
	"\x12GetJobStatsRequest\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1f\n" +
	"\vtime_period\x18\x03 \x01(\tR\n" +
	"timePeriod\"\xbf\x05\n" +
	"\bJobStats\x12\x1d\n" +
	"\n" +
	"total_jobs\x18\x01 \x01(\x05R\ttotalJobs\x12\x1f\n" +
	"\vactive_jobs\x18\x02 \x01(\x05R\n" +
	"activeJobs\x12\x1f\n" +
	"\vremote_jobs\x18\x03 \x01(\x05R\n" +
	"remoteJobs\x12p\n" +
	"\x18jobs_by_experience_level\x18\x04 \x03(\v27.jobzee.job_service.JobStats.JobsByExperienceLevelEntryR\x15jobsByExperienceLevel\x12Z\n" +
	"\x10jobs_by_location\x18\x05 \x03(\v20.jobzee.job_service.JobStats.JobsByLocationEntryR\x0ejobsByLocation\x12W\n" +
	"\x0fjobs_by_company\x18\x06 \x03(\v2/.jobzee.job_service.JobStats.JobsByCompanyEntryR\rjobsByCompany\x12\x1d\n" +
	"\n" +
	"top_skills\x18\a \x03(\tR\ttopSkills\x12=\n" +
	"\flast_updated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1aH\n" +
	"\x1aJobsByExperienceLevelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aA\n" +
	"\x13JobsByLocationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a@\n" +
	"\x12JobsByCompanyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xbe\x04\n" +
	"\n" +
	"JobService\x12J\n" +
	"\tCreateJob\x12$.jobzee.job_service.CreateJobRequest\x1a\x17.jobzee.job_service.Job\x12D\n" +
	"\x06GetJob\x12!.jobzee.job_service.GetJobRequest\x1a\x17.jobzee.job_service.Job\x12U\n" +
	"\bListJobs\x12#.jobzee.job_service.ListJobsRequest\x1a$.jobzee.job_service.ListJobsResponse\x12J\n" +
	"\tUpdateJob\x12$.jobzee.job_service.UpdateJobRequest\x1a\x17.jobzee.job_service.Job\x12I\n" +
	"\tDeleteJob\x12$.jobzee.job_service.DeleteJobRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\n" +
	"SearchJobs\x12%.jobzee.job_service.SearchJobsRequest\x1a&.jobzee.job_service.SearchJobsResponse\x12S\n" +
	"\vGetJobStats\x12&.jobzee.job_service.GetJobStatsRequest\x1a\x1c.jobzee.job_service.JobStatsBR\n" +
	"\x15com.jobzee.jobserviceP\x01Z7github.com/jobzee/jobzee-backend/proto/job_serviceb\x06proto3"

var (
	file_grpc_job_service_proto_rawDescOnce sync.Once
	file_grpc_job_service_proto_rawDescData []byte
)

func file_grpc_job_service_proto_rawDescGZIP() []byte {
	file_grpc_job_service_proto_rawDescOnce.Do(func() {
		file_grpc_job_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_job_service_proto_rawDesc), len(file_grpc_job_service_proto_rawDesc)))
	})
	return file_grpc_job_service_proto_rawDescData
}

var file_grpc_job_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_grpc_job_service_proto_goTypes = []any{
	(*Job)(nil),                   // 0: jobzee.job_service.Job
	(*CreateJobRequest)(nil),      // 1: jobzee.job_service.CreateJobRequest
	(*GetJobRequest)(nil),         // 2: jobzee.job_service.GetJobRequest
	(*ListJobsRequest)(nil),       // 3: jobzee.job_service.ListJobsRequest
	(*ListJobsResponse)(nil),      // 4: jobzee.job_service.ListJobsResponse
	(*UpdateJobRequest)(nil),      // 5: jobzee.job_service.UpdateJobRequest
	(*DeleteJobRequest)(nil),      // 6: jobzee.job_service.DeleteJobRequest
	(*SearchJobsRequest)(nil),     // 7: jobzee.job_service.SearchJobsRequest
	(*SearchJobsResponse)(nil),    // 8: jobzee.job_service.SearchJobsResponse
	(*GetJobStatsRequest)(nil),    // 9: jobzee.job_service.GetJobStatsRequest
	(*JobStats)(nil),              // 10: jobzee.job_service.JobStats
	nil,                           // 11: jobzee.job_service.JobStats.JobsByExperienceLevelEntry
	nil,                           // 12: jobzee.job_service.JobStats.JobsByLocationEntry
	nil,                           // 13: jobzee.job_service.JobStats.JobsByCompanyEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_grpc_job_service_proto_depIdxs = []int32{
	14, // 0: jobzee.job_service.Job.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: jobzee.job_service.Job.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: jobzee.job_service.ListJobsResponse.jobs:type_name -> jobzee.job_service.Job
	0,  // 3: jobzee.job_service.UpdateJobRequest.job:type_name -> jobzee.job_service.Job
	0,  // 4: jobzee.job_service.SearchJobsResponse.jobs:type_name -> jobzee.job_service.Job
	11, // 5: jobzee.job_service.JobStats.jobs_by_experience_level:type_name -> jobzee.job_service.JobStats.JobsByExperienceLevelEntry
	12, // 6: jobzee.job_service.JobStats.jobs_by_location:type_name -> jobzee.job_service.JobStats.JobsByLocationEntry
	13, // 7: jobzee.job_service.JobStats.jobs_by_company:type_name -> jobzee.job_service.JobStats.JobsByCompanyEntry
	14, // 8: jobzee.job_service.JobStats.last_updated:type_name -> google.protobuf.Timestamp
	1,  // 9: jobzee.job_service.JobService.CreateJob:input_type -> jobzee.job_service.CreateJobRequest
	2,  // 10: jobzee.job_service.JobService.GetJob:input_type -> jobzee.job_service.GetJobRequest
	3,  // 11: jobzee.job_service.JobService.ListJobs:input_type -> jobzee.job_service.ListJobsRequest
	5,  // 12: jobzee.job_service.JobService.UpdateJob:input_type -> jobzee.job_service.UpdateJobRequest
	6,  // 13: jobzee.job_service.JobService.DeleteJob:input_type -> jobzee.job_service.DeleteJobRequest
	7,  // 14: jobzee.job_service.JobService.SearchJobs:input_type -> jobzee.job_service.SearchJobsRequest
	9,  // 15: jobzee.job_service.JobService.GetJobStats:input_type -> jobzee.job_service.GetJobStatsRequest
	0,  // 16: jobzee.job_service.JobService.CreateJob:output_type -> jobzee.job_service.Job
	0,  // 17: jobzee.job_service.JobService.GetJob:output_type -> jobzee.job_service.Job
	4,  // 18: jobzee.job_service.JobService.ListJobs:output_type -> jobzee.job_service.ListJobsResponse
	0,  // 19: jobzee.job_service.JobService.UpdateJob:output_type -> jobzee.job_service.Job
	15, // 20: jobzee.job_service.JobService.DeleteJob:output_type -> google.protobuf.Empty
	8,  // 21: jobzee.job_service.JobService.SearchJobs:output_type -> jobzee.job_service.SearchJobsResponse
	10, // 22: jobzee.job_service.JobService.GetJobStats:output_type -> jobzee.job_service.JobStats
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_grpc_job_service_proto_init() }
func file_grpc_job_service_proto_init() {
	if File_grpc_job_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_job_service_proto_rawDesc), len(file_grpc_job_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_job_service_proto_goTypes,
		DependencyIndexes: file_grpc_job_service_proto_depIdxs,
		MessageInfos:      file_grpc_job_service_proto_msgTypes,
	}.Build()
	File_grpc_job_service_proto = out.File
	file_grpc_job_service_proto_goTypes = nil
	file_grpc_job_service_proto_depIdxs = nil
}
